variables:
- name: 'AzureDevOps_EnvironmentName'
  value: 'APIM-Dev'
- name: 'AzureSubscription'
  value: 'CMFG NonProduction ITPortfolio'
- name: 'API_Def'
  value: 'commercial-apim-metadata.json'
- name: 'Environment'
  value: 'dev'
- name: 'backend_uri'
  value: 'https://chatdev.trustage.com/mailboxapi'
- name: 'SubscriptionKey'
  value: 'ff82bdd25929491aa8acdca6fc2de4b2'
- name: 'RoleGroupName'
  value: 'R-App-TruChat-NonProd' 
- name: 'URL'
  value: 'dev-apimanager.trustage.com'
- name: 'Product_def'
  value: 'dev-product.json'
- name: 'OpenidConfigApim'
  value: 'openid-configuration-cmm'
- name: 'OpenidconnectAuthApim'
  value: 'openid-connect-authorization-cmm'