variables:
- name: 'AzureDevOps_EnvironmentName'
  value: 'APIM-Prod'
- name: 'AzureSubscription'
  value: 'CMFG Production ITPortfolio'
- name: 'API_Def'
  value: 'compliance-alerts-apim-metadata.json'
- name: 'Environment'
  value: 'prod'
- name: 'backend_uri'
  value: 'https://chat.trustage.com'
- name: 'SubscriptionKey'
  value: '75c3c5bf53374678a60c321a67f151b6'
- name: 'RoleGroupName'
  value: 'R-App-TruChat-Prod' 
- name: 'URL'
  value: 'apimanager.trustage.com'
- name: 'Product_def'
  value: 'prod-product.json'
- name: 'OpenidConfigApim'
  value: 'openid-configuration'
- name: 'OpenidconnectAuthApim'
  value: 'openid-connect-authorization'