parameters:
- name: AzureDevOps_EnvironmentName
  type: string
- name: AzureSubscription
  type: string
- name: Product_def
  type: string
- name: Environment
  type: string
- name: FolderPath
  type: string

stages:
 - stage: AddAPIToProduct
   displayName: 'Add API To Product'
   dependsOn:
   pool:
    vmImage: 'windows-latest'
   jobs:
    - deployment: AddAPIToProduct
      displayName: 'Add API to Product'
      environment: ${{ parameters.AzureDevOps_EnvironmentName}}
      strategy:
        runOnce:
         deploy:
          steps:
          - checkout: self
          - checkout: AzureAPIM
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '${{ parameters.AzureSubscription}}'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/AzureAPIM/AddApiToProduct.ps1'
              ScriptArguments: '-FileName "${{ parameters.Product_def}}" -Environment "${{ parameters.Environment}}" -FolderPath "${{ parameters.FolderPath}}"'
              azurePowerShellVersion: 'LatestVersion'