# Backend RBAC Template
# Configures RBAC permissions for backend services

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: resourceGroupName
  type: string
- name: enabled
  type: boolean
  default: false

jobs:
- job: docIngestionApiRBAC
  displayName: 'Configure Document Ingestion API RBAC'
  pool:
    name: "Release-ITPortfolio-NP"
  condition: eq('${{ parameters.enabled }}', 'true')
  steps:
    - checkout: self
      clean: true
      
    - task: AzurePowerShell@5
      displayName: "Get Resource IDs for Backend RBAC"
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        ScriptType: 'InlineScript'
        Inline: |
          $localrgname = "${{ parameters.resourceGroupName }}"
          
          # Determine environment prefix
          $environment = "${{ parameters.environment }}"
          $envPrefix = switch ($environment.ToLower()) {
            "prod" { "p01" }
            "demo" { "m01" }
            "dev"  { "d01" }
            default { "d01" }
          }
          
          # Set ACR ID based on environment
          $acrId = if ("${{ parameters.environment }}" -eq "prod") {
            "/subscriptions/94f0eebc-4d31-4d69-bc92-dfc97103744a/resourceGroups/rg-cmfg-p01-psa-cognitiveservices-tf/providers/Microsoft.ContainerRegistry/registries/acraiservicesprod"
          } else {
            "/subscriptions/059ed1ab-6824-4344-9a65-a0504248340f/resourceGroups/rg-cmfg-d01-psa-cognitiveservices-tf/providers/Microsoft.ContainerRegistry/registries/acraiservicesnonprod"
          }
          Write-Host "##vso[task.setvariable variable=acrId]$acrId"
          $doc_ingestionapi_sami = (Get-AzContainerApp -ResourceGroupName $localrgname | Where-Object Name -eq "ca-$envPrefix-ai-doc-ingestionapi-tf").IdentityPrincipalId
          Write-Host "##vso[task.setvariable variable=doc_ingestionapi_sami]$doc_ingestionapi_sami"
          write-host "$doc_ingestionapi_sami"
          $saidlocal = (Get-AZStorageAccount -ResourceGroupName $localrgname).Id
          Write-Host "##vso[task.setvariable variable=said]$saidlocal"
          $ssvcidlocal = (Get-AzResource -ResourceGroupName $localrgname | where-object resourcetype -eq "Microsoft.Search/searchServices").ResourceID
          Write-Host "##vso[task.setvariable variable=ssvcid]$ssvcidlocal"
          $oaiidlocal = (Get-AzCognitiveServicesAccount -ResourceGroupName $localrgname | Where-Object AccountType -eq "OpenAI").id
          $oaiidlocal1 = $oaiidlocal[0]
          $oaiidlocal2 = $oaiidlocal[1]
          $oaiidlocal3 = $oaiidlocal[2]
          Write-Host "##vso[task.setvariable variable=oaiid1]$oaiidlocal1"
          Write-Host "##vso[task.setvariable variable=oaiid2]$oaiidlocal2"
          Write-Host "##vso[task.setvariable variable=oaiid3]$oaiidlocal3"
          $cdbidlocal = (Get-AzResource -ResourceGroupName $localrgname | where-object resourcetype -eq "Microsoft.DocumentDB/databaseAccounts").Id
          Write-Host "##vso[task.setvariable variable=cdbid]$cdbidlocal"
          $cdbname = (Get-AzResource -ResourceGroupName $localrgname | where-object resourcetype -eq "Microsoft.DocumentDB/databaseAccounts").Name
          Write-Host "##vso[task.setvariable variable=cdbname]$cdbname"
          $kv_idlocal = (Get-AzKeyVault -VaultName  "kv-$envPrefix-ai-cognitive-tf").ResourceId
          Write-Host "##vso[task.setvariable variable=kv_id]$kv_idlocal"
          $fridlocal = (Get-AzCognitiveServicesAccount -ResourceGroupName $localrgname | Where-Object AccountType -eq "FormRecognizer").id
          Write-Host "##vso[task.setvariable variable=frid]$fridlocal"
        azurePowerShellVersion: 'LatestVersion'
      enabled: true

    - task: AzureCLI@2
      displayName: "custom Role for Cosmos DB"
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az cosmosdb sql role assignment create -a $(cdbname) -g ${{ parameters.resourceGroupName }} -s "/" -p $(doc_ingestionapi_sami) -d 00000000-0000-0000-0000-000000000002'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Storage Blob Data Contributor for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(said)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Storage Blob Data Contributor'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Storage Queue Data Contributor for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(said)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Storage Queue Data Contributor'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cosmos DB Operator for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(cdbid)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cosmos DB Operator'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services OpenAI User for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(oaiid1)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services OpenAI User'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services OpenAI User for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(oaiid2)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services OpenAI User'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services OpenAI User for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(oaiid3)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services OpenAI User'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Key vault secrets officer for commercial mailbox api system Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(kv_id)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Key Vault Secrets Officer'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Key vault reader for commercial mailbox api system Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(kv_id)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Key Vault Reader'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services User for system Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(oaiid1)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services User'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services User for system Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(oaiid2)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services User'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services User for system Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(oaiid3)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services User'
      enabled: true  
    - task: deployAzureRbacChanges@1
      displayName: "acrpull for commercial mailbox api container app system Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(acrId)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'AcrPull'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Cognitive Services User for Form Recognizer"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(frid)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Cognitive Services User'
      enabled: true
    - task: deployAzureRbacChanges@1
      displayName: "Search Index Data Contributor for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(ssvcid)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Search Index Data Contributor'
      enabled: true
      condition: succeededOrFailed()

    - task: deployAzureRbacChanges@1
      displayName: "Search Service Contributor for User Assigned Managed Identity"
      inputs:
        ConnectedServiceNameARM: '${{ parameters.serviceConnection }}'
        resourceId: $(ssvcid)
        identity: $(doc_ingestionapi_sami)
        permissionsAction: 'permissionAdd'
        permissions: 'Search Service Contributor'
      enabled: true
      condition: succeededOrFailed()